Repository XavierSchiller/OsuIndiaBotJS, pull requests merged in 2019-05, with the labels that each got.

#5 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#6 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#7 Pull request templates
  .github/PULL_REQUEST_TEMPLATE/bug_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/change_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/fr_pr_template.md
Labels: enhancement

#8 Update Contribution Guidelines
  CONTRIBUTING.md
Labels: change, enhancement

#12 Naming Changes and Various Function Call methods changed
  src/clients/discord.js
  src/clients/nedb.js
  src/clients/osu.js
  src/osuCommands/GetRecent.js
  src/osuCommands/GetUserBest.js
  src/osuCommands/setUser.js
  src/osuCommands/userProfile.js
Labels: change

#14 Update Issue Templates
  .github/ISSUE_TEMPLATE/change.md
  .github/ISSUE_TEMPLATE/design-review.md
  .github/ISSUE_TEMPLATE/discussion.md
Labels: enhancement

#17 Add Checklist
  .github/PULL_REQUEST_TEMPLATE/bug_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/change_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/fr_pr_template.md
  .github/pull_request_template.md
Labels: change
